---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install xorg tools
  pacman:
    name:
      - xorg-xinit
      - xorg-xmodmap
      - xorg-xdpyinfo
      - xorg-xev
      - xorg-xprop
      - xorg-sessreg
      - xautomation
      - xclip
    state: present

- name: Install video driver(s)
  pacman:
    state: present
    name: "{{ video_drivers }}"

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes
  tags:
    - user

- name: Enable middle-click scrolling
  template: src=30-scroll.conf dest=/etc/X11/xorg.conf.d/30-scroll.conf
  when: libinput.middle_click_scroll is defined
  tags:
    - libinput

- name: Remap mouse buttons
  template: src=30-button_mapping.conf dest=/etc/X11/xorg.conf.d/30-button_mapping.conf
  when: libinput.button_mapping is defined
  tags:
    - libinput

- include: sxhkd.yml
- include: unclutter.yml
- include: autorandr.yml
- include: srandrd.yml
- include: termite.yml
- include: autocutsel.yml
- include: xdg.yml
