---
- name: Install LibreOffice
  pacman: name=libreoffice-fresh state=present

- name: Install Zathura and dependencies
  pacman:
    state: present
    name:
      - zathura-pdf-mupdf
      - zathura-ps

- name: Set Zathura as default PDF viewer
  lineinfile: dest=/etc/xdg/mimeapps.list
              regexp=^application/pdf
              state=present
              line="application/pdf=zathura.desktop"
