---
- name: Create user group
  group: name={{ user.group }} state=present
  tags:
    - user

- name: Create user and assign to group
  user: name={{ user.name }} group={{ user.group }} shell={{ user.shell }} uid={{ user.uid }} groups={{ user.groups }} append=yes
  tags:
    - user

- name: Create user socket directory
  file: path=/run/user/{{ user.uid }} state=directory owner={{ user.name }} group={{ user.group }} mode=0700
  tags:
    - user

- name: Start user systemd instance
  service: name="user@{{ user.uid }}" state=started
  notify: stop systemd per-user instance
  tags:
    - user
